### ISSUE TITLE
Provide an actual specification (i.e. BNF or equivalent form)

### ISSUE THREAD

**Issue by cipriancraciun** [SixArm/usv#1]
The readme doesn't actually give a specification for USV (as does for example the linked IANA TSV <https://www.iana.org/assignments/media-types/text/tab-separated-values>).  Such a specification is necessary to make sure everyone is interpreting the examples and descriptions correctly.

Based on the single example, my interpretation is as follows:

~~~~
USV := File ( <U+241C> FILE ) *
File := Group ( <U+241D> Group ) *
Group := Record ( <U+241E> Record ) *
Record := Unit ( <U+241F> Unit ) *
Unit := < any valid UTF-8 sequence, with the exception of Unicode FS, GS, RS and US separators >
~~~~

**Comment by joelparkerhenderson** [comment]
Yes you're right that's needed. I've just added a BNF pseudocode section-- can you take a look?

Yes your interpretation is correct, with one minor adjustment: any of the items can be empty. 

For example, a unit can be an empty string, a record can contain zero units, a group can contain zero records (with zero units), a file can contain zero groups (with zero ecords and zero units).

How would you spec this?

**Comment by cipriancraciun** [comment]
I've looked at the spec and I think it has a few problems:

~~~~
unit ::= [character]+ # All characters except the 4 separators
~~~~

This should be `unit ::= [character]* # All...`, i.e. `*` instead of `+`.

~~~~
units ::= unit ( unit_separator unit ) *

record ::= [units]*
~~~~

These can be simplified as: `record ::= ( unit ( unit_separator unit ) * ) ?`

The same simplification should be made to the others `groups`, `files`, etc.

----

This is not just a matter of style, because with your BNF the following construct is also valid `unit unit unit` (as opposed to `unit unit_separator unit ...`);  thus in real terms the string `abc` can be interpreted (according to the BNF) as either one unit, either three units (`a`, `b`, `c`), or any unit combination of units that concatenate to `abc`, including any infinite number of empty units.

**Comment by joelparkerhenderson** [comment]
Yes good. I'm new to BNF. You know more than I do about it. Would you be able to write it exactly how you want it? If so, I can make the edits; if you prefer to do a pull request that's great too, and then shows that you're a contributor. Thanks!

**Comment by ptman** [comment]
Provide a test suite for implementors. Like properly handling escaping etc. Normalization could also be helpful. But don't do multiple normalization modes like XML.

**Comment by joelparkerhenderson** [comment]
Done. There's full source code now, including a test suite, in the Rust usv crate at https://github.com/sixarm/usv-rust-crate

More tests to come, and more languages to come, and there are presumably bugs to fix, and optimizations to do.
