### ISSUE TITLE
Will adding SOH be useful?

### ISSUE THREAD

**Issue by tanquar** [SixArm/usv#8]
Taking a look at the unicode block, I noticed "SOH" (start of header) and hit an idea.
Would it be nice to have SOH to distinguish whether the first row of data is header or data content?

When first row is header:
```
SOH
id US name US age RS?
SOT
1 US Alice US 32 RS
2 US Bert US 32
```

When first row is data:
```
SOT?
1 US Alice US 32 RS
2 US Bert US 32
```

**Comment by joelparkerhenderson** [comment]
Thanks for the idea. SOH can be useful for anyone who wants it, and can be put within USV data. SOH isn't good within USV itself because USV is aiming to be as simple as possible; defining header areas is not in the intended scope.
